# Numpy Basics

This is the most used Python libraries for data science. NumPy consists of a powerful data structure called multidimensional arrays. Pandas is another powerful Python library that provides fast and easy data analysis platform.

NumPy is a library written for scientific computing and data analysis. It stands for numerical python and also known as array oriented computing.

The most basic object in NumPy is the ndarray, or simply an array which is an n-dimensional, homogeneous array. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which is commonly numeric (float or integer).


 # Why Numpy?
 convenience & speed
 
 Numpy is much faster than the standard python ways to do computations.
 
Vectorised code typically does not contain explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

Also, many Numpy operations are implemented in C which is basically being executed behind the scenes, avoiding the general cost of loops in Python, pointer indirection and per-element dynamic type checking. The speed boost depends on which operations you're performing.
 
 NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

In [2]:
import numpy

In [ ]:
numpy.array([1,2,3])

In [3]:
import numpy as np

In [ ]:
a = np.array([1,2,3])

In [ ]:
a

In [ ]:
b = np.array([[1,2,3],[4,5,6]])

In [ ]:
b

In [ ]:
b.shape

In [ ]:
a.shape

In [ ]:
b.dtype

In [ ]:
b.ndim

In [ ]:
print(type(a))

In [ ]:
print(type(b))

In [ ]:
np.arange(10)

# Performance measurement
The key advantages of numpy are convenience and speed of computation.

You'll often work with extremely large datasets, and thus it is important point for you to understand how much computation time (and memory) you can save using numpy, compared to standard python lists.

In [ ]:
c = range(10000)
%timeit [i**3 for i in c]

In [ ]:
c_numpy = np.arange(10000)
%timeit c_numpy**3

Still not convinced? want to see one more intresting example

In [ ]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]

In [ ]:
%timeit list(map(lambda x, y: x*y, l1, l2))

In [ ]:
a1 = np.array(l1)
b1 = np.array(l2)

In [ ]:
%timeit a1*b1

In [ ]:
a1

In [ ]:
a1 * a1

We can do everything without even writing a loop? yes... ohh wao

# Creating Numpy array

There are multiple ways to create numpy array. Lets walk over them

In [ ]:
np.arange(2,12)

In [ ]:
np.arange(2,12,2)

In [ ]:
np.zeros((3,2))

In [ ]:
np.ones((3,2))

In [ ]:
np.eye(3)

In [ ]:
np.full((3,3),2)

In [ ]:
np.full((3,3),2.2, dtype= np.int)

In [ ]:
np.diag([1,2,3,4,5])

In [ ]:
v = np.array([1,2,3])
np.tile(v,(3,1)) # stack 3 copies of v on top of each other

In [ ]:
# between 0 and 1
np.random.random()

In [ ]:
# so let say I want a random value between 2 and 50
50*np.random.random()+2

In [ ]:
np.random.random([3,3])

In [ ]:
# 100 values between 1 and 50
a = np.linspace(1,50,100)

In [ ]:
a

In [ ]:
#memory used by each array element in bytes
a.itemsize

In [ ]:
np.arange(24)

In [ ]:
np.arange(18).reshape(2,3,3)

In [ ]:
# -1 will automatically adjust dimention
np.arange(18).reshape(2,3,-1)

# Accessing Numpy array element

In [ ]:
a = np.array([2,4,6,8,10,12,14,16])

In [ ]:
a

In [ ]:
a[2]

In [ ]:
a[[2,4,6]]

In [ ]:
a[2:]

In [ ]:
a[2:5]

In [ ]:
a[0::2]

Lets check the same for 2 D array

In [4]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a[2,2]

9

In [7]:
a > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
a[a > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
a[(a > 2) & (a < 5)]

array([3, 4])

# Subset of numpy array

In [ ]:
a = np.arange(10)

In [ ]:
b = a

In [ ]:
b

In [ ]:
b[0] = 11

In [ ]:
b

In [ ]:
# Notice a is also changed
a

In [ ]:
np.shares_memory?

In [ ]:
np.shares_memory(a,b)

In [ ]:
a = np.arange(10)

In [ ]:
b = a.copy()

In [ ]:
b[0] = 11

In [ ]:
b



In [ ]:
np.shares_memory(a,b)

In [ ]:
a

# More operations

In [ ]:
a = np.array([[1,2,3],[4,5,6]])

In [ ]:
a


In [ ]:
a.T

In [ ]:
b = np.array([[7,8,9],[10,11,12]])

In [ ]:
a

In [ ]:
b

In [ ]:
a == b

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((a,b))

# MAthmatical operation

In [ ]:
a = np.arange(1,10)

In [ ]:
np.sin(a)

In [ ]:
np.cos(a)

In [ ]:
np.exp(a)

In [ ]:
np.sum(a)

In [ ]:
np.median(a)

In [ ]:
a.std()

In [2]:
a = np.arange(1,10).reshape(3,3)

NameError: name 'np' is not defined

In [ ]:
np.linalg.det(a)

In [ ]:
np.linalg.inv(a)

In [ ]:
np.linalg.eig(a)

In [ ]:
a

In [ ]:
b = a.T

In [ ]:
b

In [1]:
np.dot(a,b)

NameError: name 'np' is not defined

In [5]:
import numpy as np
a = np.array([1,1,0], dtype = bool)
b = np.array([1,0,1], dtype = bool)
np.dot(a,b)

True

In [ ]:
np.logical_or(a,b)

In [ ]:
np.logical_and(a,b)

In [ ]:
np.all(a == a)

In [ ]:
a = np.array([[1,2],[3,4]])

In [ ]:
a

In [ ]:
a.sum()

In [ ]:
a.sum(axis=0)

In [ ]:
a.sum(axis=1)

In [ ]:
a.max()

In [ ]:
a.argmax()

In [ ]:
a

In [ ]:
a.shape

In [ ]:
a[:,np.newaxis].shape # adds a new axis -> 2D

In [ ]:
np.sort(a)

In [ ]:
np.argsort(a)